<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>js 错误处理-throw、try和catch</title>

    <script>
        function message() {
            var txt = "";
            try {
                addlert("Welcome guest");
            } catch(err) {
                txt = "本页有一个错误. \n\n"
                txt = "错误描述\n" + err.message + "\n\n";
                txt+= "点击确定继续.\n\n";
            }
            console.log(txt);
        }

        message();

        // Throw语句
            // 允许创建自定义错误；创建或抛出异常
        function testThrow() {
            var message, x;
            message = document.getElementById("message");
            message.innerHTML = "";

            x = document.getElementById("demo").value;

            try{
                if(x == "") throw "值为空";
                if(isNaN(x)) throw "不是数字";
                x = Number(x);
                if(x < 5) throw "太小";
                if(x > 10) throw "太大";
            } catch(err){
                message.innerHTML = "错误: " + err;
            }
        }



    </script>
</head>
<body>

    <div>
        <div>

            <p> 请输出一个5 到 10 之间的数字</p>

            <input id="demo" type="text">
            <button type="button" onclick="testThrow()">测试输入</button>
            <p id="message"></p>

            
        </div>
    </div>
    
</body>
</html>